[package]
name = "hp-log"
version = "0.1.0"
authors = ["junyan.yjy <junyan.yjy@alibaba-inc.com>"]
edition = "2018"

[dependencies]
strfmt = "*"
time = "*"
serde = "*"
serde_derive = "*"
toml = "*"
lazy_static = "1.1.0"
